import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import {
  closeSync,
  createReadStream,
  createWriteStream,
  fsyncSync,
  openSync,
  readSync,
  statSync,
  writeSync,
} from "node:fs";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";

import { secret } from "../src/server/config";

const keyPattern = /^[0-9a-f]{64}$/u;
export const flushDirectory = (directory: string) => {
  const fd = openSync(directory, "r");
  try {
    fsyncSync(fd);
  } finally {
    closeSync(fd);
  }
};
const chunks = async function* chunks(source: ReadableStream<Uint8Array>) {
  const reader = source.getReader();
  try {
    while (true) {
      // oxlint-disable-next-line eslint/no-await-in-loop, react-doctor/async-await-in-loop -- Consume one bounded stream chunk at a time.
      const chunk = await reader.read();
      if (chunk.done) {
        return;
      }
      yield chunk.value;
    }
  } finally {
    reader.releaseLock();
  }
};
const key = () => {
  const value = secret("PR0_BACKUP_KEY");
  if (!keyPattern.test(value)) {
    throw new Error(
      "PR0_BACKUP_KEY must be 32 randomly generated bytes encoded as lowercase hex"
    );
  }
  return Buffer.from(value, "hex");
};

// Fixed format: 12-byte nonce, streaming AES-256-GCM ciphertext, 16-byte tag.
// AAD binds the archive identity and payload purpose to prevent substitution.
export const encryptBackup = async (
  source: ReadableStream<Uint8Array>,
  filename: string,
  context: string
) => {
  const nonce = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", key(), nonce);
  cipher.setAAD(Buffer.from(`pr0-backup-v1:${context}`));
  const fd = openSync(filename, "wx", 0o600);
  try {
    writeSync(fd, nonce);
    await pipeline(
      Readable.from(chunks(source)),
      cipher,
      createWriteStream(filename, { fd, autoClose: false, start: 12 })
    );
    writeSync(fd, cipher.getAuthTag(), 0, 16, statSync(filename).size);
    fsyncSync(fd);
  } finally {
    closeSync(fd);
  }
};

export const decryptBackup = async (
  filename: string,
  destination: string,
  context: string
) => {
  const { size } = statSync(filename);
  if (size < 28) {
    throw new Error("Incomplete encrypted backup");
  }
  const fd = openSync(filename, "r");
  const nonce = Buffer.alloc(12);
  const tag = Buffer.alloc(16);
  try {
    readSync(fd, nonce, 0, 12, 0);
    readSync(fd, tag, 0, 16, size - 16);
  } finally {
    closeSync(fd);
  }
  const decipher = createDecipheriv("aes-256-gcm", key(), nonce);
  decipher.setAAD(Buffer.from(`pr0-backup-v1:${context}`));
  decipher.setAuthTag(tag);
  await pipeline(
    createReadStream(filename, { start: 12, end: size - 17 }),
    decipher,
    createWriteStream(destination, { flags: "wx", mode: 0o600 })
  );
};
