[package]
name = "pr0-desktop"
version = "0.1.0"
description = "pr0 desktop application"
edition = "2021"
rust-version = "1.94"
publish = false

[lib]
name = "pr0_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
