param([Parameter(Mandatory=$true)][string]$Directory)
$taskKey = [System.Security.Cryptography.RSA]::Create(2048)
$taskRequest = [System.Security.Cryptography.X509Certificates.CertificateRequest]::new('CN=localhost', $taskKey, [System.Security.Cryptography.HashAlgorithmName]::SHA256, [System.Security.Cryptography.RSASignaturePadding]::Pkcs1)
$taskNames = [System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder]::new()
$taskNames.AddDnsName('localhost')
$taskRequest.CertificateExtensions.Add($taskNames.Build())
$taskRequest.CertificateExtensions.Add([System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension]::new($false,$false,0,$true))
$taskCertificate = $taskRequest.CreateSelfSigned([DateTimeOffset]::UtcNow.AddMinutes(-5), [DateTimeOffset]::UtcNow.AddDays(1))
[System.IO.File]::WriteAllText((Join-Path $Directory 'certificate.pem'), $taskCertificate.ExportCertificatePem())
[System.IO.File]::WriteAllText((Join-Path $Directory 'key.pem'), $taskKey.ExportPkcs8PrivateKeyPem())
$taskCertificate.Dispose()
$taskKey.Dispose()
