// Unicode 17.0.0 inputs are vendored with the Unicode license; no host ICU is used.
const root = new URL("../", import.meta.url);
const read = async (name: string) => {
  const source = await Bun.file(
    new URL(`unicode/17.0.0/${name}.txt`, root)
  ).text();
  return source.split("\n");
};
const [data, folding, properties, normalization] = await Promise.all([
  read("UnicodeData"),
  read("CaseFolding"),
  read("PropList"),
  read("DerivedNormalizationProps"),
]);
const property = (lines: string[], name: string) => {
  const result = new Set<number>();
  for (const line of lines) {
    const [range, prop] = (line.split("#")[0] ?? "")
      .split(";")
      .map((part) => part.trim());
    if (prop !== name || !range) {
      continue;
    }
    const [start, end = start] = range
      .split("..")
      .map((value) => Number.parseInt(value, 16));
    if (start === undefined || end === undefined) {
      continue;
    }
    for (let cp = start; cp <= end; cp += 1) {
      result.add(cp);
    }
  }
  return result;
};
const exclusions = property(normalization, "Full_Composition_Exclusion");
const diacritics = property(properties, "Diacritic");
const whitespace = [...property(properties, "White_Space")];
const combining: Record<number, number> = {};
const decomposition: Record<number, number[]> = {};
const composition: Record<string, number> = {};
const marks: number[] = [];
for (const line of data) {
  const [hex, , category, cls, , mapping] = line.split(";");
  if (!hex) {
    continue;
  }
  const cp = Number.parseInt(hex, 16);
  if (Number(cls)) {
    combining[cp] = Number(cls);
  }
  if (category?.startsWith("M") && diacritics.has(cp)) {
    marks.push(cp);
  }
  if (mapping && !mapping.startsWith("<")) {
    const values = mapping
      .split(" ")
      .map((value) => Number.parseInt(value, 16));
    decomposition[cp] = values;
    if (values.length === 2 && !exclusions.has(cp)) {
      composition[values.join(",")] = cp;
    }
  }
}
const casefold: Record<number, number[]> = {};
for (const line of folding) {
  const [hex, status, mapping] = (line.split("#")[0] ?? "")
    .split(";")
    .map((part) => part.trim());
  if (hex && mapping && (status === "C" || status === "F")) {
    casefold[Number.parseInt(hex, 16)] = mapping
      .split(" ")
      .map((value) => Number.parseInt(value, 16));
  }
}
const tables = {
  combining,
  decomposition,
  composition,
  casefold,
  marks,
  whitespace,
};
await Bun.write(
  new URL("src/unicode17-data.json", root),
  `${JSON.stringify(tables)}\n`
);
const pairs = (entries: Record<number, number[]>) =>
  Object.entries(entries)
    .map(([cp, values]) => `(${cp}, &[${values.join(",")}])`)
    .join(",\n");
// Native lookup tables are generated from the same inputs as the TypeScript JSON.
await Bun.write(
  new URL("unicode/unicode17.rs", root),
  `// Generated by scripts/generate-unicode.ts. Unicode license: LICENSE.txt.
pub const UNICODE_VERSION: &str = "17.0.0";
pub const COMBINING: &[(u32, u8)] = &[${Object.entries(combining)
    .map(([cp, cls]) => `(${cp},${cls})`)
    .join(",\n")}];
pub const DECOMPOSITION: &[(u32, &[u32])] = &[${pairs(decomposition)}];
pub const CASEFOLD: &[(u32, &[u32])] = &[${pairs(casefold)}];
pub const COMPOSITION: &[((u32, u32), u32)] = &[${Object.entries(composition)
    .map(([pair, cp]) => `((${pair}),${cp})`)
    .join(",\n")}];
pub const DIACRITIC_MARKS: &[u32] = &[${marks.join(",")}];
pub const WHITE_SPACE: &[u32] = &[${whitespace.join(",")}];
`
);
